--Input for JBOOST generated by Excel

--


--    Definition Modelname
local	ModelName="V236 - DP-A PreFeed L0.G0.S0"
--    Definition der FE-Knoten

os_FeNode{model=ModelName,	node=501,	x=0,	y=0,	z=-27.13,	pMass=00000,	pInertia=0,	pOutOfVertically=00.000}
os_FeNode{model=ModelName,	node=502,	x=0,	y=0,	z=-24.80,	pMass=00000,	pInertia=0,	pOutOfVertically=00.043}
os_FeNode{model=ModelName,	node=503,	x=0,	y=0,	z=-20.80,	pMass=00000,	pInertia=0,	pOutOfVertically=00.116}
os_FeNode{model=ModelName,	node=504,	x=0,	y=0,	z=-18.30,	pMass=00000,	pInertia=0,	pOutOfVertically=00.162}
os_FeNode{model=ModelName,	node=505,	x=0,	y=0,	z=-14.40,	pMass=00000,	pInertia=0,	pOutOfVertically=00.233}
os_FeNode{model=ModelName,	node=506,	x=0,	y=0,	z=-10.50,	pMass=00000,	pInertia=0,	pOutOfVertically=00.305}
os_FeNode{model=ModelName,	node=507,	x=0,	y=0,	z=-08.52,	pMass=00000,	pInertia=0,	pOutOfVertically=00.341}	 --additionally generated
os_FeNode{model=ModelName,	node=508,	x=0,	y=0,	z=-06.60,	pMass=00000,	pInertia=0,	pOutOfVertically=00.376}
os_FeNode{model=ModelName,	node=509,	x=0,	y=0,	z=-02.70,	pMass=00000,	pInertia=0,	pOutOfVertically=00.448}
os_FeNode{model=ModelName,	node=510,	x=0,	y=0,	z=-01.00,	pMass=01600,	pInertia=0,	pOutOfVertically=00.479}	 --additionally generated
os_FeNode{model=ModelName,	node=511,	x=0,	y=0,	z=00.00,	pMass=05500,	pInertia=0,	pOutOfVertically=00.497}	 --additionally generated
os_FeNode{model=ModelName,	node=512,	x=0,	y=0,	z=00.90,	pMass=00000,	pInertia=0,	pOutOfVertically=00.514}
os_FeNode{model=ModelName,	node=513,	x=0,	y=0,	z=01.48,	pMass=00000,	pInertia=0,	pOutOfVertically=00.524}	-- Waterlevel
os_FeNode{model=ModelName,	node=514,	x=0,	y=0,	z=03.48,	pMass=00000,	pInertia=0,	pOutOfVertically=00.561}	 --additionally generated
os_FeNode{model=ModelName,	node=515,	x=0,	y=0,	z=04.20,	pMass=00000,	pInertia=0,	pOutOfVertically=00.574}
os_FeNode{model=ModelName,	node=516,	x=0,	y=0,	z=06.00,	pMass=11650,	pInertia=0,	pOutOfVertically=00.607}	 --additionally generated
os_FeNode{model=ModelName,	node=517,	x=0,	y=0,	z=06.50,	pMass=00000,	pInertia=0,	pOutOfVertically=00.616}	 --additionally generated
os_FeNode{model=ModelName,	node=518,	x=0,	y=0,	z=07.50,	pMass=00000,	pInertia=0,	pOutOfVertically=00.635}
os_FeNode{model=ModelName,	node=519,	x=0,	y=0,	z=10.00,	pMass=01600,	pInertia=0,	pOutOfVertically=00.681}	 --additionally generated
os_FeNode{model=ModelName,	node=520,	x=0,	y=0,	z=11.50,	pMass=00000,	pInertia=0,	pOutOfVertically=00.708}
os_FeNode{model=ModelName,	node=521,	x=0,	y=0,	z=12.00,	pMass=06150,	pInertia=0,	pOutOfVertically=00.717}	 --additionally generated
os_FeNode{model=ModelName,	node=522,	x=0,	y=0,	z=12.13,	pMass=02800,	pInertia=0,	pOutOfVertically=00.720}	 --additionally generated
os_FeNode{model=ModelName,	node=523,	x=0,	y=0,	z=14.07,	pMass=04600,	pInertia=0,	pOutOfVertically=00.755}	 --additionally generated
os_FeNode{model=ModelName,	node=524,	x=0,	y=0,	z=14.37,	pMass=06400,	pInertia=0,	pOutOfVertically=00.761}	 --additionally generated
os_FeNode{model=ModelName,	node=525,	x=0,	y=0,	z=14.75,	pMass=00000,	pInertia=0,	pOutOfVertically=00.768}
os_FeNode{model=ModelName,	node=526,	x=0,	y=0,	z=17.00,	pMass=02900,	pInertia=0,	pOutOfVertically=00.809}	 --additionally generated
os_FeNode{model=ModelName,	node=527,	x=0,	y=0,	z=17.40,	pMass=01250,	pInertia=0,	pOutOfVertically=00.816}	 --additionally generated
os_FeNode{model=ModelName,	node=528,	x=0,	y=0,	z=18.50,	pMass=01450,	pInertia=0,	pOutOfVertically=00.836}
os_FeNode{model=ModelName,	node=529,	x=0,	y=0,	z=19.00,	pMass=00900,	pInertia=0,	pOutOfVertically=00.845}	 --additionally generated
os_FeNode{model=ModelName,	node=530,	x=0,	y=0,	z=20.10,	pMass=03800,	pInertia=0,	pOutOfVertically=00.866}	 --additionally generated
os_FeNode{model=ModelName,	node=531,	x=0,	y=0,	z=21.10,	pMass=35450,	pInertia=0,	pOutOfVertically=00.884}	 --additionally generated
os_FeNode{model=ModelName,	node=601,	x=0,	y=0,	z=21.30,	pMass=15006,	pInertia=0,	pOutOfVertically=00.888}
os_FeNode{model=ModelName,	node=602,	x=0,	y=0,	z=21.48,	pMass=13586,	pInertia=0,	pOutOfVertically=00.891}
os_FeNode{model=ModelName,	node=603,	x=0,	y=0,	z=21.55,	pMass=00053,	pInertia=0,	pOutOfVertically=00.892}
os_FeNode{model=ModelName,	node=604,	x=0,	y=0,	z=22.30,	pMass=01000,	pInertia=0,	pOutOfVertically=00.906}	 --additionally generated
os_FeNode{model=ModelName,	node=605,	x=0,	y=0,	z=23.98,	pMass=03295,	pInertia=0,	pOutOfVertically=00.937}
os_FeNode{model=ModelName,	node=606,	x=0,	y=0,	z=25.42,	pMass=09063,	pInertia=0,	pOutOfVertically=00.963}
os_FeNode{model=ModelName,	node=607,	x=0,	y=0,	z=25.45,	pMass=00081,	pInertia=0,	pOutOfVertically=00.964}
os_FeNode{model=ModelName,	node=608,	x=0,	y=0,	z=26.95,	pMass=00000,	pInertia=0,	pOutOfVertically=00.991}
os_FeNode{model=ModelName,	node=609,	x=0,	y=0,	z=29.55,	pMass=00158,	pInertia=0,	pOutOfVertically=01.039}
os_FeNode{model=ModelName,	node=610,	x=0,	y=0,	z=29.88,	pMass=00000,	pInertia=0,	pOutOfVertically=01.045}
os_FeNode{model=ModelName,	node=611,	x=0,	y=0,	z=31.30,	pMass=00158,	pInertia=0,	pOutOfVertically=01.071}
os_FeNode{model=ModelName,	node=612,	x=0,	y=0,	z=32.81,	pMass=00000,	pInertia=0,	pOutOfVertically=01.099}
os_FeNode{model=ModelName,	node=613,	x=0,	y=0,	z=33.67,	pMass=00158,	pInertia=0,	pOutOfVertically=01.114}
os_FeNode{model=ModelName,	node=614,	x=0,	y=0,	z=35.74,	pMass=00000,	pInertia=0,	pOutOfVertically=01.152}
os_FeNode{model=ModelName,	node=615,	x=0,	y=0,	z=37.80,	pMass=00158,	pInertia=0,	pOutOfVertically=01.190}
os_FeNode{model=ModelName,	node=616,	x=0,	y=0,	z=38.67,	pMass=00138,	pInertia=0,	pOutOfVertically=01.206}
os_FeNode{model=ModelName,	node=617,	x=0,	y=0,	z=40.17,	pMass=01424,	pInertia=0,	pOutOfVertically=01.233}
os_FeNode{model=ModelName,	node=618,	x=0,	y=0,	z=41.28,	pMass=00006,	pInertia=0,	pOutOfVertically=01.254}
os_FeNode{model=ModelName,	node=619,	x=0,	y=0,	z=41.47,	pMass=12629,	pInertia=0,	pOutOfVertically=01.257}
os_FeNode{model=ModelName,	node=620,	x=0,	y=0,	z=41.67,	pMass=08431,	pInertia=0,	pOutOfVertically=01.261}
os_FeNode{model=ModelName,	node=621,	x=0,	y=0,	z=41.72,	pMass=00151,	pInertia=0,	pOutOfVertically=01.262}
os_FeNode{model=ModelName,	node=622,	x=0,	y=0,	z=44.51,	pMass=00150,	pInertia=0,	pOutOfVertically=01.313}
os_FeNode{model=ModelName,	node=623,	x=0,	y=0,	z=47.30,	pMass=00150,	pInertia=0,	pOutOfVertically=01.364}
os_FeNode{model=ModelName,	node=624,	x=0,	y=0,	z=50.10,	pMass=00000,	pInertia=0,	pOutOfVertically=01.415}
os_FeNode{model=ModelName,	node=625,	x=0,	y=0,	z=50.17,	pMass=00000,	pInertia=0,	pOutOfVertically=01.417}
os_FeNode{model=ModelName,	node=626,	x=0,	y=0,	z=51.30,	pMass=00150,	pInertia=0,	pOutOfVertically=01.437}
os_FeNode{model=ModelName,	node=627,	x=0,	y=0,	z=52.90,	pMass=00000,	pInertia=0,	pOutOfVertically=01.467}
os_FeNode{model=ModelName,	node=628,	x=0,	y=0,	z=54.30,	pMass=00149,	pInertia=0,	pOutOfVertically=01.492}
os_FeNode{model=ModelName,	node=629,	x=0,	y=0,	z=55.70,	pMass=00000,	pInertia=0,	pOutOfVertically=01.518}
os_FeNode{model=ModelName,	node=630,	x=0,	y=0,	z=58.42,	pMass=00149,	pInertia=0,	pOutOfVertically=01.568}
os_FeNode{model=ModelName,	node=631,	x=0,	y=0,	z=58.50,	pMass=00149,	pInertia=0,	pOutOfVertically=01.569}
os_FeNode{model=ModelName,	node=632,	x=0,	y=0,	z=61.29,	pMass=00000,	pInertia=0,	pOutOfVertically=01.621}
os_FeNode{model=ModelName,	node=633,	x=0,	y=0,	z=61.31,	pMass=00000,	pInertia=0,	pOutOfVertically=01.621}
os_FeNode{model=ModelName,	node=634,	x=0,	y=0,	z=62.55,	pMass=00148,	pInertia=0,	pOutOfVertically=01.644}
os_FeNode{model=ModelName,	node=635,	x=0,	y=0,	z=64.10,	pMass=00105,	pInertia=0,	pOutOfVertically=01.672}
os_FeNode{model=ModelName,	node=636,	x=0,	y=0,	z=66.09,	pMass=00000,	pInertia=0,	pOutOfVertically=01.709}
os_FeNode{model=ModelName,	node=637,	x=0,	y=0,	z=66.67,	pMass=00105,	pInertia=0,	pOutOfVertically=01.719}
os_FeNode{model=ModelName,	node=638,	x=0,	y=0,	z=68.09,	pMass=01905,	pInertia=0,	pOutOfVertically=01.745}
os_FeNode{model=ModelName,	node=639,	x=0,	y=0,	z=69.01,	pMass=00001,	pInertia=0,	pOutOfVertically=01.762}
os_FeNode{model=ModelName,	node=640,	x=0,	y=0,	z=70.13,	pMass=00006,	pInertia=0,	pOutOfVertically=01.782}
os_FeNode{model=ModelName,	node=641,	x=0,	y=0,	z=70.31,	pMass=10681,	pInertia=0,	pOutOfVertically=01.786}
os_FeNode{model=ModelName,	node=642,	x=0,	y=0,	z=70.50,	pMass=07571,	pInertia=0,	pOutOfVertically=01.789}
os_FeNode{model=ModelName,	node=643,	x=0,	y=0,	z=70.54,	pMass=00143,	pInertia=0,	pOutOfVertically=01.790}
os_FeNode{model=ModelName,	node=644,	x=0,	y=0,	z=73.26,	pMass=00000,	pInertia=0,	pOutOfVertically=01.840}
os_FeNode{model=ModelName,	node=645,	x=0,	y=0,	z=74.92,	pMass=00143,	pInertia=0,	pOutOfVertically=01.870}
os_FeNode{model=ModelName,	node=646,	x=0,	y=0,	z=75.99,	pMass=00142,	pInertia=0,	pOutOfVertically=01.890}
os_FeNode{model=ModelName,	node=647,	x=0,	y=0,	z=78.72,	pMass=00000,	pInertia=0,	pOutOfVertically=01.940}
os_FeNode{model=ModelName,	node=648,	x=0,	y=0,	z=79.04,	pMass=00142,	pInertia=0,	pOutOfVertically=01.946}
os_FeNode{model=ModelName,	node=649,	x=0,	y=0,	z=81.30,	pMass=00000,	pInertia=0,	pOutOfVertically=01.987}
os_FeNode{model=ModelName,	node=650,	x=0,	y=0,	z=81.44,	pMass=00000,	pInertia=0,	pOutOfVertically=01.990}
os_FeNode{model=ModelName,	node=651,	x=0,	y=0,	z=83.17,	pMass=00141,	pInertia=0,	pOutOfVertically=02.022}
os_FeNode{model=ModelName,	node=652,	x=0,	y=0,	z=84.17,	pMass=00141,	pInertia=0,	pOutOfVertically=02.040}
os_FeNode{model=ModelName,	node=653,	x=0,	y=0,	z=86.91,	pMass=00000,	pInertia=0,	pOutOfVertically=02.090}
os_FeNode{model=ModelName,	node=654,	x=0,	y=0,	z=87.29,	pMass=00140,	pInertia=0,	pOutOfVertically=02.097}
os_FeNode{model=ModelName,	node=655,	x=0,	y=0,	z=89.64,	pMass=00000,	pInertia=0,	pOutOfVertically=02.140}
os_FeNode{model=ModelName,	node=656,	x=0,	y=0,	z=91.30,	pMass=00140,	pInertia=0,	pOutOfVertically=02.171}
os_FeNode{model=ModelName,	node=657,	x=0,	y=0,	z=92.38,	pMass=00139,	pInertia=0,	pOutOfVertically=02.190}
os_FeNode{model=ModelName,	node=658,	x=0,	y=0,	z=95.12,	pMass=00000,	pInertia=0,	pOutOfVertically=02.241}
os_FeNode{model=ModelName,	node=659,	x=0,	y=0,	z=95.54,	pMass=00139,	pInertia=0,	pOutOfVertically=02.248}
os_FeNode{model=ModelName,	node=660,	x=0,	y=0,	z=97.86,	pMass=00000,	pInertia=0,	pOutOfVertically=02.291}
os_FeNode{model=ModelName,	node=661,	x=0,	y=0,	z=99.67,	pMass=00138,	pInertia=0,	pOutOfVertically=02.324}
os_FeNode{model=ModelName,	node=662,	x=0,	y=0,	z=100.61,	pMass=00000,	pInertia=0,	pOutOfVertically=02.341}
os_FeNode{model=ModelName,	node=663,	x=0,	y=0,	z=101.30,	pMass=00078,	pInertia=0,	pOutOfVertically=02.354}
os_FeNode{model=ModelName,	node=664,	x=0,	y=0,	z=102.61,	pMass=01578,	pInertia=0,	pOutOfVertically=02.378}
os_FeNode{model=ModelName,	node=665,	x=0,	y=0,	z=103.71,	pMass=00001,	pInertia=0,	pOutOfVertically=02.398}
os_FeNode{model=ModelName,	node=666,	x=0,	y=0,	z=103.75,	pMass=00005,	pInertia=0,	pOutOfVertically=02.399}
os_FeNode{model=ModelName,	node=667,	x=0,	y=0,	z=103.91,	pMass=07646,	pInertia=0,	pOutOfVertically=02.402}
os_FeNode{model=ModelName,	node=668,	x=0,	y=0,	z=104.07,	pMass=05549,	pInertia=0,	pOutOfVertically=02.405}
os_FeNode{model=ModelName,	node=669,	x=0,	y=0,	z=104.11,	pMass=00147,	pInertia=0,	pOutOfVertically=02.405}
os_FeNode{model=ModelName,	node=670,	x=0,	y=0,	z=107.04,	pMass=00000,	pInertia=0,	pOutOfVertically=02.459}
os_FeNode{model=ModelName,	node=671,	x=0,	y=0,	z=107.91,	pMass=00147,	pInertia=0,	pOutOfVertically=02.475}
os_FeNode{model=ModelName,	node=672,	x=0,	y=0,	z=109.97,	pMass=00000,	pInertia=0,	pOutOfVertically=02.513}
os_FeNode{model=ModelName,	node=673,	x=0,	y=0,	z=111.30,	pMass=00147,	pInertia=0,	pOutOfVertically=02.537}
os_FeNode{model=ModelName,	node=674,	x=0,	y=0,	z=112.90,	pMass=00147,	pInertia=0,	pOutOfVertically=02.566}
os_FeNode{model=ModelName,	node=675,	x=0,	y=0,	z=115.83,	pMass=00000,	pInertia=0,	pOutOfVertically=02.620}
os_FeNode{model=ModelName,	node=676,	x=0,	y=0,	z=116.16,	pMass=00147,	pInertia=0,	pOutOfVertically=02.626}
os_FeNode{model=ModelName,	node=677,	x=0,	y=0,	z=118.76,	pMass=00000,	pInertia=0,	pOutOfVertically=02.674}
os_FeNode{model=ModelName,	node=678,	x=0,	y=0,	z=121.21,	pMass=00991,	pInertia=0,	pOutOfVertically=02.719}
os_FeNode{model=ModelName,	node=679,	x=0,	y=0,	z=121.69,	pMass=00127,	pInertia=0,	pOutOfVertically=02.728}
os_FeNode{model=ModelName,	node=680,	x=0,	y=0,	z=124.23,	pMass=00000,	pInertia=0,	pOutOfVertically=02.774}
os_FeNode{model=ModelName,	node=681,	x=0,	y=0,	z=124.41,	pMass=00127,	pInertia=0,	pOutOfVertically=02.777}
os_FeNode{model=ModelName,	node=682,	x=0,	y=0,	z=126.76,	pMass=00000,	pInertia=0,	pOutOfVertically=02.820}
os_FeNode{model=ModelName,	node=683,	x=0,	y=0,	z=128.54,	pMass=00127,	pInertia=0,	pOutOfVertically=02.853}
os_FeNode{model=ModelName,	node=684,	x=0,	y=0,	z=130.31,	pMass=00083,	pInertia=0,	pOutOfVertically=02.886}
os_FeNode{model=ModelName,	node=685,	x=0,	y=0,	z=130.94,	pMass=00899,	pInertia=0,	pOutOfVertically=02.897}
os_FeNode{model=ModelName,	node=686,	x=0,	y=0,	z=131.30,	pMass=00000,	pInertia=0,	pOutOfVertically=02.904}
os_FeNode{model=ModelName,	node=687,	x=0,	y=0,	z=131.73,	pMass=22980,	pInertia=0,	pOutOfVertically=02.911}
os_FeNode{model=ModelName,	node=688,	x=0,	y=0,	z=132.54,	pMass=00081,	pInertia=0,	pOutOfVertically=02.926}
os_FeNode{model=ModelName,	node=689,	x=0,	y=0,	z=134.16,	pMass=04666,	pInertia=0,	pOutOfVertically=02.956}
os_FeNode{model=ModelName,	node=690,	x=0,	y=0,	z=135.79,	pMass=00944,	pInertia=0,	pOutOfVertically=02.986}
os_FeNode{model=ModelName,	node=691,	x=0,	y=0,	z=136.55,	pMass=22980,	pInertia=0,	pOutOfVertically=03.000}
os_FeNode{model=ModelName,	node=692,	x=0,	y=0,	z=137.39,	pMass=00082,	pInertia=0,	pOutOfVertically=03.015}
os_FeNode{model=ModelName,	node=693,	x=0,	y=0,	z=139.81,	pMass=00831,	pInertia=0,	pOutOfVertically=03.060}
os_FeNode{model=ModelName,	node=694,	x=0,	y=0,	z=140.69,	pMass=00002,	pInertia=0,	pOutOfVertically=03.076}
os_FeNode{model=ModelName,	node=695,	x=0,	y=0,	z=140.74,	pMass=00005,	pInertia=0,	pOutOfVertically=03.077}
os_FeNode{model=ModelName,	node=696,	x=0,	y=0,	z=140.91,	pMass=06026,	pInertia=0,	pOutOfVertically=03.080}
os_FeNode{model=ModelName,	node=800,	x=0,	y=0,	z=144.499,	pMass=808850,	pInertia=223000000,	pOutOfVertically=03.146}

--Definition der FE-Elemente- Zusatzmassen in kg/m   

os_FeElem{model=ModelName,	elem_id= 001,	startnode=501,	endnode=502,	diameter=8.90,	t_wall=0.088,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 002,	startnode=502,	endnode=503,	diameter=8.90,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 003,	startnode=503,	endnode=504,	diameter=8.90,	t_wall=0.088,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 004,	startnode=504,	endnode=505,	diameter=8.73,	t_wall=0.088,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 005,	startnode=505,	endnode=506,	diameter=8.38,	t_wall=0.086,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 006,	startnode=506,	endnode=507,	diameter=8.11,	t_wall=0.086,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 007,	startnode=507,	endnode=508,	diameter=7.94,	t_wall=0.086,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 008,	startnode=508,	endnode=509,	diameter=7.68,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 009,	startnode=509,	endnode=510,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 010,	startnode=510,	endnode=511,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 011,	startnode=511,	endnode=512,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 012,	startnode=512,	endnode=513,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}		-- Waterlevel
os_FeElem{model=ModelName,	elem_id= 013,	startnode=513,	endnode=514,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 014,	startnode=514,	endnode=515,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 015,	startnode=515,	endnode=516,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 016,	startnode=516,	endnode=517,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 017,	startnode=517,	endnode=518,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 018,	startnode=518,	endnode=519,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 019,	startnode=519,	endnode=520,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 020,	startnode=520,	endnode=521,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 021,	startnode=521,	endnode=522,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 022,	startnode=522,	endnode=523,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 023,	startnode=523,	endnode=524,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 024,	startnode=524,	endnode=525,	diameter=7.50,	t_wall=0.090,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 025,	startnode=525,	endnode=526,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 026,	startnode=526,	endnode=527,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 027,	startnode=527,	endnode=528,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 028,	startnode=528,	endnode=529,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 029,	startnode=529,	endnode=530,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 030,	startnode=530,	endnode=531,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 031,	startnode=531,	endnode=601,	diameter=7.50,	t_wall=0.087,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 032,	startnode=601,	endnode=602,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 033,	startnode=602,	endnode=603,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 034,	startnode=603,	endnode=604,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 035,	startnode=604,	endnode=605,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 036,	startnode=605,	endnode=606,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 037,	startnode=606,	endnode=607,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 038,	startnode=607,	endnode=608,	diameter=7.50,	t_wall=0.080,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 039,	startnode=608,	endnode=609,	diameter=7.48,	t_wall=0.049,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 040,	startnode=609,	endnode=610,	diameter=7.47,	t_wall=0.049,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 041,	startnode=610,	endnode=611,	diameter=7.46,	t_wall=0.041,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 042,	startnode=611,	endnode=612,	diameter=7.46,	t_wall=0.041,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 043,	startnode=612,	endnode=613,	diameter=7.46,	t_wall=0.040,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 044,	startnode=613,	endnode=614,	diameter=7.46,	t_wall=0.040,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 045,	startnode=614,	endnode=615,	diameter=7.46,	t_wall=0.039,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 046,	startnode=615,	endnode=616,	diameter=7.46,	t_wall=0.039,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 047,	startnode=616,	endnode=617,	diameter=7.46,	t_wall=0.038,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 048,	startnode=617,	endnode=618,	diameter=7.46,	t_wall=0.045,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 049,	startnode=618,	endnode=619,	diameter=7.47,	t_wall=0.045,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 050,	startnode=619,	endnode=620,	diameter=7.47,	t_wall=0.045,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 051,	startnode=620,	endnode=621,	diameter=7.47,	t_wall=0.045,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 052,	startnode=621,	endnode=622,	diameter=7.44,	t_wall=0.039,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 053,	startnode=622,	endnode=623,	diameter=7.40,	t_wall=0.037,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 054,	startnode=623,	endnode=624,	diameter=7.35,	t_wall=0.037,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 055,	startnode=624,	endnode=625,	diameter=7.33,	t_wall=0.036,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 056,	startnode=625,	endnode=626,	diameter=7.32,	t_wall=0.036,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 057,	startnode=626,	endnode=627,	diameter=7.30,	t_wall=0.036,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 058,	startnode=627,	endnode=628,	diameter=7.28,	t_wall=0.036,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 059,	startnode=628,	endnode=629,	diameter=7.26,	t_wall=0.036,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 060,	startnode=629,	endnode=630,	diameter=7.23,	t_wall=0.035,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 061,	startnode=630,	endnode=631,	diameter=7.21,	t_wall=0.035,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 062,	startnode=631,	endnode=632,	diameter=7.19,	t_wall=0.035,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 063,	startnode=632,	endnode=633,	diameter=7.16,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 064,	startnode=633,	endnode=634,	diameter=7.16,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 065,	startnode=634,	endnode=635,	diameter=7.13,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 066,	startnode=635,	endnode=636,	diameter=7.11,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 067,	startnode=636,	endnode=637,	diameter=7.09,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 068,	startnode=637,	endnode=638,	diameter=7.07,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 069,	startnode=638,	endnode=639,	diameter=7.05,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 070,	startnode=639,	endnode=640,	diameter=7.03,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 071,	startnode=640,	endnode=641,	diameter=7.03,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 072,	startnode=641,	endnode=642,	diameter=7.03,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 073,	startnode=642,	endnode=643,	diameter=7.03,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 074,	startnode=643,	endnode=644,	diameter=7.00,	t_wall=0.034,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 075,	startnode=644,	endnode=645,	diameter=6.95,	t_wall=0.032,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 076,	startnode=645,	endnode=646,	diameter=6.91,	t_wall=0.032,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 077,	startnode=646,	endnode=647,	diameter=6.87,	t_wall=0.032,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 078,	startnode=647,	endnode=648,	diameter=6.83,	t_wall=0.031,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 079,	startnode=648,	endnode=649,	diameter=6.80,	t_wall=0.031,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 080,	startnode=649,	endnode=650,	diameter=6.77,	t_wall=0.031,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 081,	startnode=650,	endnode=651,	diameter=6.75,	t_wall=0.031,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 082,	startnode=651,	endnode=652,	diameter=6.71,	t_wall=0.031,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 083,	startnode=652,	endnode=653,	diameter=6.67,	t_wall=0.030,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 084,	startnode=653,	endnode=654,	diameter=6.63,	t_wall=0.030,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 085,	startnode=654,	endnode=655,	diameter=6.60,	t_wall=0.030,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 086,	startnode=655,	endnode=656,	diameter=6.55,	t_wall=0.030,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 087,	startnode=656,	endnode=657,	diameter=6.52,	t_wall=0.030,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 088,	startnode=657,	endnode=658,	diameter=6.47,	t_wall=0.029,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 089,	startnode=658,	endnode=659,	diameter=6.43,	t_wall=0.029,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 090,	startnode=659,	endnode=660,	diameter=6.40,	t_wall=0.029,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 091,	startnode=660,	endnode=661,	diameter=6.35,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 092,	startnode=661,	endnode=662,	diameter=6.31,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 093,	startnode=662,	endnode=663,	diameter=6.29,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 094,	startnode=663,	endnode=664,	diameter=6.28,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 095,	startnode=664,	endnode=665,	diameter=6.25,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 096,	startnode=665,	endnode=666,	diameter=6.23,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 097,	startnode=666,	endnode=667,	diameter=6.23,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 098,	startnode=667,	endnode=668,	diameter=6.23,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 099,	startnode=668,	endnode=669,	diameter=6.23,	t_wall=0.028,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 100,	startnode=669,	endnode=670,	diameter=6.23,	t_wall=0.026,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 101,	startnode=670,	endnode=671,	diameter=6.23,	t_wall=0.026,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 102,	startnode=671,	endnode=672,	diameter=6.23,	t_wall=0.026,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 103,	startnode=672,	endnode=673,	diameter=6.23,	t_wall=0.025,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 104,	startnode=673,	endnode=674,	diameter=6.23,	t_wall=0.025,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 105,	startnode=674,	endnode=675,	diameter=6.22,	t_wall=0.025,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 106,	startnode=675,	endnode=676,	diameter=6.22,	t_wall=0.024,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 107,	startnode=676,	endnode=677,	diameter=6.22,	t_wall=0.024,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 108,	startnode=677,	endnode=678,	diameter=6.22,	t_wall=0.024,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 109,	startnode=678,	endnode=679,	diameter=6.22,	t_wall=0.024,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 110,	startnode=679,	endnode=680,	diameter=6.22,	t_wall=0.024,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 111,	startnode=680,	endnode=681,	diameter=6.22,	t_wall=0.023,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 112,	startnode=681,	endnode=682,	diameter=6.22,	t_wall=0.023,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 113,	startnode=682,	endnode=683,	diameter=6.22,	t_wall=0.023,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 114,	startnode=683,	endnode=684,	diameter=6.22,	t_wall=0.023,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 115,	startnode=684,	endnode=685,	diameter=6.22,	t_wall=0.022,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 116,	startnode=685,	endnode=686,	diameter=6.24,	t_wall=0.050,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 117,	startnode=686,	endnode=687,	diameter=6.25,	t_wall=0.050,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 118,	startnode=687,	endnode=688,	diameter=6.25,	t_wall=0.050,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 119,	startnode=688,	endnode=689,	diameter=6.24,	t_wall=0.029,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 120,	startnode=689,	endnode=690,	diameter=6.23,	t_wall=0.033,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 121,	startnode=690,	endnode=691,	diameter=6.24,	t_wall=0.050,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 122,	startnode=691,	endnode=692,	diameter=6.25,	t_wall=0.050,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 123,	startnode=692,	endnode=693,	diameter=6.08,	t_wall=0.042,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 124,	startnode=693,	endnode=694,	diameter=5.76,	t_wall=0.042,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 125,	startnode=694,	endnode=695,	diameter=5.62,	t_wall=0.042,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 126,	startnode=695,	endnode=696,	diameter=5.62,	t_wall=0.042,	EModul=2.10E+11,	fyk=355,	poisson=0.3,	dens=7850,	addMass=0,	member_id=1}
os_FeElem{model=ModelName,	elem_id= 127,	startnode=696,	endnode=800,	diameter=5.62,	t_wall=0.042,	EModul=2.10E+14,	fyk=355,	poisson=0.3,	dens=1,	addMass=0,	member_id=1}
